name: CI

on:
  pull_request:
  push:
    branches:
      - main

# recommended: reset permissions and explicitly specify for each job
permissions: {}

# recommended: avoid concurrent runs for the same ref, cancel superseded runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read # to check out repo (actions/checkout)
    steps:
      - name: Check out repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Install pnpm and Node.js and Install dependencies
        uses: pnpm/setup@c8e77b72cd6022852162c92aa10e7e72b7209c9b # v2
        with:
          cache: true

      - name: Lint and format check
        run: pnpm check

      - name: Run tests
        run: pnpm test

      - name: Build
        run: pnpm build
